[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-ue-cpp"
description = "C++ grammar with Unreal Engine declaration macro support"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
dependencies = ["tree-sitter~=0.25"]
